apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: olss-demo-app
  namespace: monitoring
spec:
  targetLabels:
    - olss-demo-app
  selector:
    matchLabels:
      app: olss-demo-app
  namespaceSelector:
    matchNames:
      - olss-demo-app
  endpoints:
  - port: web
    path: /actuator/prometheus
