server:
  tomcat:
    accesslog:
      enabled: true
      suffix: ""
      directory: /dev
      prefix: stdout
      file-date-format: ""
      buffered: false
      
olss:
  uuid: ${random.uuid}
  
management:
  metrics:
    tags:
      app.name: olss-demo-app
      app.uuid: ${olss.uuid}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
        - metrics