apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: olss-demo-app
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: olss-demo-app
              servicePort: 8080
