name: OLSS hands on: autolabel new issues

on: 
  issues:
    types: 
      - opened

jobs:
  add-olss-label:
    runs-on: ubuntu-latest

    steps:
    - uses: Renato66/auto-label@v2
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        default-labels: '["olss"]'
